### ISSUE TITLE
przenoszenie urządzenia

### ISSUE THREAD

**Issue by serwisZiA** [dzemba1986/wachowiakisyn#1]
Przy przenoszeniu abonenta wytnij -wklej oraz przy przenoszeniu sprzętu, trzeba usunąć opcje:
"Brak wolnych portów",
"Brak miejsca na liście"
Powoduje utracenie dostępu do całej gałęzi

**Comment by serwisZiA** [comment]
Przy zmianie MAC, po naciśnięciu opcji "zapisz" nie ma możliwości wygenerowania skryptu na przełącznik, póki nie ma historii zmian - może wystąpić przypadek że w momencie zapisu stracimy starego MAC i trzeba będzie zmienić z powrotem na tego go samego żeby wgrać poprawną konfigurację na przełącznik

**Comment by dzemba1986** [comment]
proszę pisać każdy problem w osobnym wątku, tytuł niech będzie krótki ale jasno opisujący problem

**Comment by serwisZiA** [comment]
Proponuję też usunąć możliwość przenoszenia głównego elementu drzewa

**Comment by dzemba1986** [comment]
Przeniesiono do wątku #25
