### ISSUE TITLE
[bo] Wygenerować raporty

### ISSUE THREAD

**Issue by serwisZiA** [dzemba1986/wachowiakisyn#13]
Proszę wygenerować raporty w CSV:

1. Listę urządzeń (przełączniki + bramki) z kolumnami: adres IP, MAC, serial, lokalizacja, nazwa.
2. Listy hostów z kolumnami: Lokalizacja, IP, MAC, Nazwa, Opis
   a) z niepustym polem Opis
   b) z niepustym polem Nazwa
   c) ze znakami inne niż litery w polu "Klatka"
   d) ze znakami inne niż cyfry w polu "Lokal"
   e) ze znakami inne niż cyfry w polu "Blok"
   f) ze wartością >= 100 w polu "Blok"

**Comment by dzemba1986** [comment]
* `2a` - wysłałem
* `2b` - pole nazwa nie może być niepuste, co najwyżej mogę posortować po tych które zawierają "[ ]" (czyli `original_name` jest `false`). Generalnie jest tu już zrobiony porządek.
* `2c` - wypluło tylko 1 hosta `OP3B1 [Prowent]`
* `2d` - wysłałem
* `2e` - wypluło tylko 1 hosta `OWW paw. 122`
* `2f` - wysłałem
