### ISSUE TITLE
[bo] Brak zestawienia wykorzystania adresów IP

### ISSUE THREAD

**Issue by serwisZiA** [dzemba1986/wachowiakisyn#14]
Proszę o dodanie zestawienia wykorzystania adresów IP, takich jak w starym SEU: 
Zestawienia -> Wykorzystanie adresów IP (https://seu-serwis.wtvk.pl/reaports/vlanIpUtilization.php)

**Comment by dzemba1986** [comment]
Wolne adresy zlicza. Niestety nie sortuje. Trzeba kiedyś wrócić do tematu.
