### ISSUE TITLE
Zmiana nr seryjnych

### ISSUE THREAD

**Issue by serwisZiA** [dzemba1986/wachowiakisyn#18]
Chcąc zmienić nr seryjny urządzenia już zamontowanego trzeba zmienić pole nazwy by móc zapisać zmiany, ale jest przy tym dodawany dopisek w nawiasie kwadratowym lub jeśli pole nazwy jest puste jest dodawany pusty nawias kwadratowy - przypadek gdzie montowane są dwa przełączniki na tym samym piętrze

**Comment by dzemba1986** [comment]
Problem rozwiązany
