### ISSUE TITLE
[bo] Nie można edytować virtualki

### ISSUE THREAD

**Issue by serwisZiA** [dzemba1986/wachowiakisyn#22]
Maciej Zdeb, OP24/48, ustawiony jest adres OP120 i nie można zmienić.

**Comment by dzemba1986** [comment]
Można edytować. Założyłem jednak że "virualka" nie będzie miała docelowo pola "lokal" - wirtualkami nie bedą mogły być hosty. Będą to tylko urządzenia do testów - można nadać nazwę swoją.
