### ISSUE TITLE
[bo] Brak adresów "do konfiguracji"

### ISSUE THREAD

**Issue by serwisZiA** [dzemba1986/wachowiakisyn#24]
Home -> Połączenia -> Do konfiguracji

Lista jest pusta :(
A powinien być np. OZ5L/27 - do cfg.
27.12.2016 został już skonfigurowany.

**Comment by dzemba1986** [comment]
Moje założenia są takie: wyświetlam wszystkie bez daty konfiguracji, bez daty rezygnacji, internety, z kablem i z mac'iem. Do poprawki jeżeli trzeba.

**Comment by dzemba1986** [comment]
Usunąłem kryterium MAC'a, kabel do ustalenia. Na dzisiaj zamykam.
