### ISSUE TITLE
Podgląd skryptu 

### ISSUE THREAD

**Issue by serwisZiA** [dzemba1986/wachowiakisyn#3]
Podgląd skryptu podczas kopiowania na przełącznik

**Comment by dzemba1986** [comment]
Zdecydowałem że jest to zbędna opcja. Jeżeli generowanie skryptu działa poprawnie to po jakimś czasie i tak nikt by nie patrzył na to co wypisuje podgląd. A jeżeli generowanie nie działa to należy to poprawić.
