### ISSUE TITLE
Wyszukiwanie urządzenia przy dodawaniu przełącznika

### ISSUE THREAD

**Issue by serwisZiA** [dzemba1986/wachowiakisyn#34]
Znów pojawia się problem z wyszukiwaniem urządzenia przy dodawaniu przełącznika i portu  w Firefox

**Comment by dzemba1986** [comment]
Na dzień dzisiejszy jest to kwestia przeglądarki. Widżet "select2" jest jakimś standardem więc zakładam że nie powinno być z nim problemów.
