### ISSUE TITLE
Wymiana bramki

### ISSUE THREAD

**Issue by serwisZiA** [dzemba1986/wachowiakisyn#36]
Problem przy wymianie bramki z magazynu:
Bramki, które są zamontowane też wyświetlają się jako widoczne w magazynie i po zaznaczeniu takiej bramki, a następnie próbie dodania jako portu INTERNET(LAN) nie można tego zapisać. W związku z brakiem wyszukiwania nie można wyszukać zamontowanej bramki w SEU. Dodatkowo przez przypadek(bądź z ciekawości) można dodać bramkę jako np. port phone1 - i w tym momencie pojawiają się dwa adresy IP w adresacji zamontowanej bramki bo była zamontowana na innej lokalizacji, Bramka jest przypisana wtedy do dwóch lokalizacji. Nie można jej usunąć z drzewa(pojawia się pusty wpis na drzewie, który tylko i wyłącznie zajmuje port na przełączniku w SEU). Danej bramki nie można też zamontować jeśli znajdzie się w magazynie - sprawa dotyczy bramki opisanej jako OP12E i bramki, która powinna znaleźć się na OK22G/10.40.1.15/OK22g-p16/bc:67:1c:95:da:58

Puste wpisy, które zajmują w tej chwili porty:
OP12E(podłączone na OK22G-p16)
OZ5N(podłączone na OZ5M-p20)

**Comment by dzemba1986** [comment]
Problem występował ponieważ podczas wymiany wyświetlały się także wszystkie urządzenia z drzewa. Na podmianę została wybrana bramka która była zamontowana na drzewie.
