### ISSUE TITLE
add voip dla x210

### ISSUE THREAD

**Issue by serwisZiA** [dzemba1986/wachowiakisyn#75]
Na OZ125 przy dodawaniu add niektóre komendy są wyświetlane kilka razy i brak w description opisu "vo":

OZ125(config)#access-list hardware voip9
OZ125(config-ip-hw-acl)#deny udp any any eq 68
OZ125(config-ip-hw-acl)#permit ip 10.28.1.32 0.0.0.0 213.5.208.0 0.0.0.63
OZ125(config-ip-hw-acl)#permit ip 10.28.1.32 0.0.0.0 213.5.208.128 0.0.0.63
OZ125(config-ip-hw-acl)#permit ip 10.28.1.32 0.0.0.0 10.111.0.0 0.0.255.255
OZ125(config-ip-hw-acl)#permit udp 0.0.0.0 0.0.0.0 eq 68 any eq 67
OZ125(config-ip-hw-acl)#permit udp 0.0.0.0 0.0.0.0 eq 68 any eq 67
OZ125(config-ip-hw-acl)#permit udp 0.0.0.0 0.0.0.0 eq 68 any eq 67
OZ125(config-ip-hw-acl)#deny ip any any
OZ125(config-ip-hw-acl)#exit
OZ125(config-ip-hw-acl)#exit
OZ125(config)#interface port1.0.9
OZ125(config)#interface port1.0.9
OZ125(config)#interface port1.0.9
OZ125(config-if)#shutdown
OZ125(config-if)#shutdown
OZ125(config-if)#description OZ125
OZ125(config-if)#description OZ125
OZ125(config-if)#description OZ125
OZ125(config-if)#switchport access vlan 3
OZ125(config-if)#switchport access vlan 3
OZ125(config-if)#access-group voip9
OZ125(config-if)#access-group voip9
OZ125(config-if)#access-group voip9
OZ125(config-if)#spanning-tree portfast
OZ125(config-if)#spanning-tree portfast bpdu-guard enable
OZ125(config-if)#spanning-tree portfast bpdu-guard enable
OZ125(config-if)#no shutdown
OZ125(config-if)#exit
OZ125(config-if)#exit
OZ125(config)#exit
OZ125#wr

**Comment by dzemba1986** [comment]
Poprawiono
