### ISSUE TITLE
Sortowanie zadań wykonanych

### ISSUE THREAD

**Issue by serwisZiA** [dzemba1986/wachowiakisyn#87]
Daniel aktualnie zadania wykonane są posortowane  od najstarszej do najnowszej a powinno być odwrotnie - najnowsze powinny być na początku. Przy kilku zadaniach nie było problemu ale obecnie są 2 strony i trzeba przewijać całą listę żeby zobaczyć aktualnie wykonane zadanie

**Comment by dzemba1986** [comment]
zrobione
